stages:
  - pre 
  - build

.go-cache: &go-cache
  key: dd-trace-dotnet-aws-lambda-layer-go-cache
  policy: pull

generator:
  stage: pre
  image: registry.ddbuild.io/images/mirror/golang:alpine
  tags: ["arch:amd64"]
  cache: *go-cache
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /external_pull_request_event|merge_request_event|push/'
      when: never
    - when: always
  script:
    - apk add --no-cache gomplate
    - gomplate --config .gitlab/config.yaml
  artifacts:
    paths:
      - .gitlab/*-pipeline.yaml

build:
  stage: build
  needs: ["generator"]
  trigger:
    include:
      - artifact: .gitlab/build-pipeline.yaml
        job: generator
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /external_pull_request_event|merge_request_event|push/'
      when: never
    - when: always
  variables:
    UPSTREAM_PIPELINE_ID: $UPSTREAM_PIPELINE_ID
    UPSTREAM_COMMIT_TAG: $UPSTREAM_COMMIT_TAG
