variables:
  DOCKER_TARGET_IMAGE: registry.ddbuild.io/ci/dd-trace-dotnet-aws-lambda-layer
  DOCKER_TARGET_VERSION: latest

stages:
  - pre 
  - build

.go-cache: &go-cache
  key: dd-trace-dotnet-aws-lambda-layer-go-cache
  policy: pull

ci image:
  stage: build
  image: registry.ddbuild.io/images/docker:20.10
  tags: ["arch:arm64"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - .gitlab/Dockerfile
      when: on_success
  variables:
    DOCKER_TARGET: ${DOCKER_TARGET_IMAGE}:${DOCKER_TARGET_VERSION}
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache --pull --push --tag ${DOCKER_TARGET} -f .gitlab/Dockerfile .

generator:
  stage: pre
  image: registry.ddbuild.io/images/mirror/golang:alpine
  tags: ["arch:amd64"]
  cache: *go-cache
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /external_pull_request_event|merge_request_event|push/'
      when: never
    - when: always
  script:
    - apk add --no-cache gomplate
    - gomplate --config .gitlab/config.yaml
  artifacts:
    paths:
      - .gitlab/build-pipeline.yaml

build:
  stage: build
  needs: ["generator"]
  trigger:
    include:
      - artifact: .gitlab/build-pipeline.yaml
        job: generator
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /external_pull_request_event|merge_request_event|push/'
      when: never
    - when: always
  variables:
    UPSTREAM_PIPELINE_ID: $UPSTREAM_PIPELINE_ID
    UPSTREAM_COMMIT_TAG: $UPSTREAM_COMMIT_TAG
