stages:
  - pre 
  - build

.go-cache: &go-cache
  key: dd-trace-dotnet-aws-lambda-layer-go-cache
  policy: pull

generator:
  stage: pre
  image: registry.ddbuild.io/images/mirror/golang:alpine
  tags: ["arch:amd64"]
  cache: *go-cache
  script:
    - apk add --no-cache gomplate
    - gomplate --config .gitlab/config.yaml
  artifacts:
    paths:
      - ci/*-pipeline.yaml

build:
  stage: build
  trigger:
    include:
      - artifact: ci/build-pipeline.yaml
        job: generator
    strategy: depend
  rules:
    - when: on_success
  variables:
    UPSTREAM_PIPELINE_ID: $UPSTREAM_PIPELINE_ID
    UPSTREAM_COMMIT_TAG: $UPSTREAM_COMMIT_TAG
