stages:
  - build

layer:
  stage: build
  image: registry.ddbuild.io/images/docker:20.10
  tags: ["arch:amd64"]
  # artifacts:
  #   expire_in: 2 weeks
  #   paths:
  #     - layer.zip
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /external_pull_request_event|merge_request_event|push/'
      when: never
    - when: always
  retry: 2
  script:
    - ./gitlab/download_tracer_artifacts.sh
    - ls -la